### ISSUE TITLE
heartbeat passed to bolt on storm 0.9.3

### ISSUE THREAD

**Issue by mdrio** [AirSage/Petrel#65]
Hi, I am using petrel on storm 0.9.3. I noticed that bolts after a while receive this tuple:

    <Tuple component=None id=u'6846907854583824214' stream=u'__heartbeat' task=-1 values=[]>

Then they stop working. It happen sometime even running the wordcount example with local topology (probably it just a matter of time).
 That tuple is not supposed to be processed by bolts, but it should be sent to Nimbus. Maybe it does not receive it, resulting in some crash (just a theory).
Any idea how to fix it?

**Comment by barrywhart** [comment]
I'm not familiar with Storm heartbeats. Is this a recent feature addition? Or an optional thing that you enabled for your topoloogy?

When this happens, is there a traceback in the Python log file? Is the Python worker still running? Could you change your bolt to ignore these tuples?

**Comment by barrywhart** [comment]
I was able to reproduce your problem in the Petrel wordcount sample on my machine. I added these two lines to the beginning of the process() function on each bolt. This avoids the crash, and probably fixes the problem.

        if tup.stream == '__heartbeat':
            return

**Comment by barrywhart** [comment]
The fix for this is not as simple as I'd hoped. It appears Storm 0.9.3 changed the API contract for Python bolts: now they receive heartbeats and are expected to respond, apparently by calling storm.sync(). I have tried this in the sample wordcount topology, but now instead of crashing as before, the bolts stop receiving tuples from Storm. I haven't found a solution yet.

If you need an immediate solution, I'd say downgrade to an earlier version of Storm. I do not believe 0.9.1 or 0.9.2 behaved this way.

Here's a URL with some background. Tons of comments on it which I need to read.
https://issues.apache.org/jira/browse/STORM-513

**Comment by barrywhart** [comment]
I have updated Petrel's storm.py based on the latest changes in Apache Storm's storm.py. This appears to have fixed the problem. With this update, there is no need to change your bolts; heartbeats are handled automatically by storm.py.

I will close the ticket. Please reopen if you still see issues with this.

**Comment by mdrio** [comment]
Great, I will test the fix today.

**Comment by mdrio** [comment]
Ok, it works!

**Comment by barrywhart** [comment]
Great! This is the first time a Storm release has broken Petrel. The last too, I hope.
