### ISSUE TITLE
Request for controlling topology name

### ISSUE THREAD

**Issue by CogumelosMaravilha** [AirSage/Petrel#77]
Hi Barry,
Lets see point by point. When I compile my topology for later submission;
petrel submit --config topology.yaml --venv self --logdir 'pwd'
$jar -xvf topology.jar |less
created: META-INF/
inflated: META-INF/MANIFEST.MF
created: storm/
created: storm/petrel/
inflated: storm/petrel/GenericTopology.class
I allway get a GenericTopology.class, and if I want to submit 2 topologies I cant because both have the same name. How can I change this name?

Hi allways submit my topology like this;
storm jar topology.jar storm.petrel.GenericTopology Generic -c strom.petrel.GenericTopology Generic -c nimbus.host=127.0.0.1

**Comment by barrywhart** [comment]
It should not be necessary to change the actual topology class name; the topology name is a higher-level label separate from the actual class name.

See the "submitTopology" function on the StormSubmitter class.

http://storm.apache.org/releases/current/Running-topologies-on-a-production-cluster.html

"petrel submit" lets you specify the topology name. I'm not familiar with the "storm jar" command. It may offer a similar capability. If you must use "storm jar" instead of "petrel submit", please check with the larger Storm community about that.
